# Generated by Erlang.mk. Edit at your own risk!

src/eredis.erl:: include/eredis.hrl; @touch $@
src/eredis_client.erl:: include/eredis.hrl; @touch $@
src/eredis_parser.erl:: include/eredis.hrl; @touch $@

COMPILE_FIRST +=
